#!name=IOS_Notifications
#!desc=APNS ON

[Rule]
DOMAIN-SUFFIX,push.apple.com,PROXY
DOMAIN-SUFFIX,akadns.net,PROXY
DOMAIN-KEYWORD,apple.com.edgekey.net,PROXY

IP-CIDR,17.249.0.0/16,PROXY,no-resolve
IP-CIDR,17.252.0.0/16,PROXY,no-resolve
IP-CIDR,17.57.144.0/22,PROXY,no-resolve
IP-CIDR,17.188.128.0/18,PROXY,no-resolve
IP-CIDR,17.188.20.0/23,PROXY,no-resolve

IP-CIDR6,2620:149:a44::/48,PROXY,no-resolve
IP-CIDR6,2403:300:a42::/48,PROXY,no-resolve
IP-CIDR6,2403:300:a51::/48,PROXY,no-resolve
IP-CIDR6,2a01:b740:a42::/48,PROXY,no-resolve
